### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by xpusostomos** [vbtrek/PlexRatingsSync#3] opened 2020-04-25 03:53 UTC
Is this broken? When I start it, the options window pops up immediately. When I close options, the rest of the app closes too.

**Comment by cjhesse** [comment] 2020-09-26 22:24
I'm seeing the same.

**Comment by vbtrek** [comment] 2022-01-21 10:58
Closed as duplicate of https://github.com/vbtrek/PlexRatingsSync/issues/7

**Closed by vbtrek** 2022-01-21 10:58 UTC
